crud:
    prefix: /admin
    controller: \Cungfoo\Controller\CrudController
    items:
        author:
            prefix: /authors
            model: \Cungfoo\Model\Author
            form: \Cungfoo\Form\Type\AuthorType
        category:
            prefix: /categories
            model: \Cungfoo\Model\Category
            form: \Cungfoo\Form\Type\CategoryType
        document:
            prefix: /documents
            model: \Cungfoo\Model\Document
            form: \Cungfoo\Form\Type\DocumentType
