crud:
    prefix: /
    controller: \Cungfoo\Controller\CrudController
    items:
        service_complementaire:
            prefix: /services-complementaires
            model: \Cungfoo\Model\ServiceComplementaire
            form: \Cungfoo\Form\Type\ServiceComplementaireType
        etablissement:
            prefix: /etablissement
            model: \Cungfoo\Model\Etablissement
            form: \Cungfoo\Form\Type\EtablissementType
        type_hebergement:
            prefix: /type-hebergement
            model: \Cungfoo\Model\TypeHebergement
            form: \Cungfoo\Form\Type\TypeHebergementType
        category_type_hebergement:
            prefix: /category-type-hebergement
            model: \Cungfoo\Model\CategoryTypeHebergement
            form: \Cungfoo\Form\Type\CategoryTypeHebergementType
        ville:
            prefix: /villes
            model: \Cungfoo\Model\Ville
            form: \Cungfoo\Form\Type\VilleType
        region:
            prefix: /regions
            model: \Cungfoo\Model\Region
            form: \Cungfoo\Form\Type\RegionType
        pays:
            prefix: /pays
            model: \Cungfoo\Model\Pays
            form: \Cungfoo\Form\Type\PaysType
        destination:
            prefix: /destinations
            model: \Cungfoo\Model\Destination
            form: \Cungfoo\Form\Type\DestinationType
        activite:
            prefix: /activites
            model: \Cungfoo\Model\Activite
            form: \Cungfoo\Form\Type\ActiviteType
