crud:
    prefix: /
    controller: \Cungfoo\Controller\CrudController
    items:
        service_complementaire:
            prefix: /services-complementaires
            model: \Cungfoo\Model\ServiceComplementaire
            form: \Cungfoo\Form\Type\ServiceComplementaireType
        etablissement:
            prefix: /etablissement
            model: \Cungfoo\Model\Etablissement
            form: \Cungfoo\Form\Type\EtablissementType
        type_hebergement:
            prefix: /type-hebergement
            model: \Cungfoo\Model\TypeHebergement
            form: \Cungfoo\Form\Type\TypeHebergementType
        category_type_hebergement:
            prefix: /category-type-hebergement
            model: \Cungfoo\Model\CategoryTypeHebergement
            form: \Cungfoo\Form\Type\CategoryTypeHebergementType
        ville:
            prefix: /villes
            model: \Cungfoo\Model\Ville
            form: \Cungfoo\Form\Type\VilleType
        region:
            prefix: /regions
            model: \Cungfoo\Model\Region
            form: \Cungfoo\Form\Type\RegionType
        pays:
            prefix: /pays
            model: \Cungfoo\Model\Pays
            form: \Cungfoo\Form\Type\PaysType
        destination:
            prefix: /destinations
            model: \Cungfoo\Model\Destination
            form: \Cungfoo\Form\Type\DestinationType
        activite:
            prefix: /activites
            model: \Cungfoo\Model\Activite
            form: \Cungfoo\Form\Type\ActiviteType
        categorie:
            prefix: /categories
            model: \Cungfoo\Model\Categorie
            form: \Cungfoo\Form\Type\CategorieType
        situation_geographique:
            prefix: /situation-geographiques
            model: \Cungfoo\Model\SituationGeographique
            form: \Cungfoo\Form\Type\SituationGeographiqueType
        baignade:
            prefix: /baignades
            model: \Cungfoo\Model\Baignade
            form: \Cungfoo\Form\Type\BaignadeType
        thematique:
            prefix: /thematiques
            model: \Cungfoo\Model\Thematique
            form: \Cungfoo\Form\Type\ThematiqueType
        point_interet:
            prefix: /points-interet
            model: \Cungfoo\Model\PointInteret
            form: \Cungfoo\Form\Type\PointInteretType
        event:
            prefix: /events
            model: \Cungfoo\Model\Event
            form: \Cungfoo\Form\Type\EventType
        personnage:
            prefix: /personnages
            model: \Cungfoo\Model\Personnage
            form: \Cungfoo\Form\Type\PersonnageType
        multimedia_etablissement:
            prefix: /multimedias
            model: \Cungfoo\Model\MultimediaEtablissement
            form: \Cungfoo\Form\Type\MultimediaEtablissementType
        tag:
            prefix: /tag-multimedias
            model: \Cungfoo\Model\Tag
            form: \Cungfoo\Form\Type\TagType
        avantage:
            prefix: /personnages-avantages
            model: \Cungfoo\Model\Avantage
            form: \Cungfoo\Form\Type\AvantageType
        edito:
            prefix: /editos
            model: \Cungfoo\Model\Edito
            form: \Cungfoo\Form\Type\EditoType
        demande_identifiant:
            prefix: /demandes_identifiant
            model: \Cungfoo\Model\DemandeIdentifiant
            form: \Cungfoo\Form\Type\DemandeIdentifiantType
        top_camping:
            prefix: /top_camping
            model: \Cungfoo\Model\TopCamping
            form: \Cungfoo\Form\Type\TopCampingType
        dernieres_minutes:
            prefix: /dernieres_minutes
            model: \Cungfoo\Model\DernieresMinutes
            form: \Cungfoo\Form\Type\DernieresMinutesType
        mise_en_avant:
            prefix: /mise_en_avant
            model: \Cungfoo\Model\MiseEnAvant
            form: \Cungfoo\Form\Type\MiseEnAvantType
        vos_vacances:
            prefix: /vos_vacances
            model: \Cungfoo\Model\VosVacances
            form: \Cungfoo\Form\Type\VosVacancesType
