menu:
    route: admin
    title: menu.title
    items:
        documents:
            title:  menu.documents
            route:  document_crud_list
        authors:
            title:  menu.authors
            route:  author_crud_list
        campings:
            title:  menu.campings
            route:  camping_crud_list
        dico:
            title:  menu.dictionaries
            items:
                categories:
                    title:  menu.categories
                    route:  category_crud_list