#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';

$app = require __DIR__ . '/app/bootstrap.php';
require __DIR__.'/app/config/prod.php';
$app->get('/', function () use ($app) {
    // reset '/' route for making 'run' possible
});

$app->run(); // to boot registered services : Propel, etc.

$console  = new \Cungfoo\Console\Application($app, 'Cungfoo', '0.1');

$console->add(new \Propel\Command\Fixtures\LoadCommand());
$console->add(new \Propel\Command\GenerateCommand());

$console->add(new \Cungfoo\Command\Cache\ClearCommand());
$console->add(new \Cungfoo\Command\Logs\ClearCommand());
$console->add(new \Cungfoo\Command\Project\InitCommand());
$console->add(new \Cungfoo\Command\Tests\UnitCommand());
$console->add(new \Cungfoo\Command\Tests\SniffCommand());

$console->add(new \Cungfoo\Command\Resalys\Load\CatalogueCommand());
$console->add(new \Cungfoo\Command\Resalys\Load\PrixCommand());
$console->add(new \Cungfoo\Command\Resalys\DumpCommand());

$console->add(new \Cungfoo\Command\Job\DaemonCommand());

$console->run();