#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/app/bootstrap.php';

$console = $app['console'];

$console->add(new \Propel\Command\Fixtures\LoadCommand());
$console->add(new \Propel\Command\GenerateCommand());
$console->add(new \Propel\Command\LoadSchemaCommand());
$console->add(new \Propel\Command\Migration\UpCommand());
$console->add(new \Propel\Command\Migration\DownCommand());

$console->add(new \Cungfoo\Command\Cache\ClearCommand());
$console->add(new \Cungfoo\Command\Logs\ClearCommand());
$console->add(new \Cungfoo\Command\Project\InitCommand());
$console->add(new \Cungfoo\Command\Project\Database\SetupCommand());
$console->add(new \Cungfoo\Command\Project\Language\SetupCommand());
$console->add(new \Cungfoo\Command\Tests\UnitCommand());
$console->add(new \Cungfoo\Command\Tests\SniffCommand());

$console->add(new \Resalys\Command\LoadCommand());
$console->add(new \Resalys\Command\Client\SetupCommand());

$console->add(new \Cungfoo\Command\Fixtures\DumpCommand());
$console->add(new \Cungfoo\Command\Fixtures\LoadCommand());
$console->add(new \Cungfoo\Command\Fixtures\Load\BinariesCommand());
$console->add(new \Cungfoo\Command\Fixtures\Load\VendorCommand());
$console->add(new \Cungfoo\Command\Fixtures\Load\BrutesCommand());

$console->add(new \Cungfoo\Command\ViaFrance\Load\PointOfInterestCommand());
$console->add(new \Cungfoo\Command\ViaFrance\Load\EventCommand());

$console->add(new \Cungfoo\Command\Job\DaemonCommand());

$console->add(new \VacancesDirectes\Command\Load\Etablissement\CoordinatesCommand());
$console->add(new \VacancesDirectes\Command\Load\Etablissement\RelatedCommand());
$console->add(new \VacancesDirectes\Command\Slug\GenerateCommand());
$console->add(new \VacancesDirectes\Command\Database\CheckIntegrityCommand());
$console->add(new \VacancesDirectes\Command\Translations\UpdateCommand());
$console->add(new \VacancesDirectes\Command\InitCommand());
$console->add(new \VacancesDirectes\Command\UpdateCommand());

$console->add(new \Cungfoo\Command\Patch\PortfolioCommand());

$console->add(new \Cungfoo\Command\Assets\JsCompileCommand());
$console->add(new \Cungfoo\Command\Assets\ImageCompileCommand());

$console->run();
