# sera peut-être utilisé pour faire le lien entre les campings et les régions
# actuellement, pour récupérer les campings d'une réégion, on récupère les viles de la région, et les campings de ces villes
# cette liste d'identifiants fait la correspondance entre les IDs Resalys et Viafrance, pour éventuellement récupérer la "vraie" région d'un camping avec une requête à viafrance
regions:
  ALP:
    departement: '73,74'
  ALJU:
    region: 'R01'
    departement: '39'
  ARDE:
    departement: '07'
  AUVE:
    region: 'R03'
  BRET:
    region: 'R05'
  CHMA:
    departement: '17'
  CORS:
    region: 'R08'
  PCA:
    departement: '83,06,04,5,13,84'
  GIRO:
    departement: '33'
  LAND:
    departement: '40'
  LARO:
    region: 'R11'
  ARPY:
    region: 'R14'
    departement: '09'
  NORM:
    region: 'R161,R162'
  PBAS:
    departement: '64'
  PLOI:
    departement: '44'
  PEDO:
    departement: '24,19,46,47'
  DRHP:
    departement: '26,04'
  VEND:
    departement: '85'
  LOCH:
    departement: '41'
  GERS:
    departement: '32'
  AVEY:
    departement: '12'
  HERA:
    departement: '34'
  AUDE:
    departement: '11'
  PASD:
    departement: '62'
  ILE:
    region: 'R12'
  PYRO:
    departement: '66'
