context:
    saison:
        saison_ete:
            title: Été
        saison_hiver:
            title: Hiver
        default: saison_ete
    locale:
        locale_fr:
            title:  Français
        locale_en:
            title:  Anglais
        default: locale_en