loader:
  RoomTypeLoader: ~
  RoomTypeCategoryLoader: ~
  ThemeLoader:
    themes:
      PAYS:
        model:  \Cungfoo\Model\Pays
      REGIONS:
        model:  \Cungfoo\Model\Region
        parent: PAYS
      VILLE:
        model:  \Cungfoo\Model\Ville
        parent: REGIONS
      SERVCOMP:
        model:  \Cungfoo\Model\ServiceComplementaire
      ACTIVITES:
        model:  \Cungfoo\Model\Activite
      EQUIP:
        model:  \Cungfoo\Model\Equipement
      DESTI:
        model:  \Cungfoo\Model\Destination
  EtabLoader:
    themes:
      VILLE:
        model:      \Cungfoo\Model\Ville
        setter:     setVille
      SERVCOMP:
        model:      \Cungfoo\Model\ServiceComplementaire
        associated: \Cungfoo\Model\EtablissementServiceComplementaire
        setter:     addServiceComplementaire
        filter:     filterByServiceComplementaireId
      ACTIVITES:
        model:      \Cungfoo\Model\Activite
        associated: \Cungfoo\Model\EtablissementActivite
        setter:     addActivite
        filter:     filterByActiviteId
      EQUIP:
        model:      \Cungfoo\Model\Equipement
        associated: \Cungfoo\Model\EtablissementEquipement
        setter:     addEquipement
        filter:     filterByEquipementId
      DESTI:
        model:      \Cungfoo\Model\Destination
        associated: \Cungfoo\Model\EtablissementDestination
        setter:     addDestination
        filter:     filterByDestinationId