loader:
  RoomTypeLoader: ~
  RoomTypeCategoryLoader: ~
  ThemeLoader:
    themes:
      PAYS:
        model:  \Cungfoo\Model\Pays
      REGIONS:
        model:  \Cungfoo\Model\Region
        parent:
          name:   PAYS
          setter: setPaysId
      VILLE:
        model:  \Cungfoo\Model\Ville
        parent:
          name:   REGIONS
          setter: setRegionId
      CATEG:
        model:  \Cungfoo\Model\Categorie
      SERVCOMP:
        model:  \Cungfoo\Model\ServiceComplementaire
      ACTIVITES:
        model:  \Cungfoo\Model\Activite
      DESTI:
        model:  \Cungfoo\Model\Destination
  EtabLoader:
    themes:
      VILLE:
        model:      \Cungfoo\Model\Ville
        setter:     setVille
      CATEG:
        model:      \Cungfoo\Model\Categorie
        setter:     setCategorie
      SERVCOMP:
        model:      \Cungfoo\Model\ServiceComplementaire
        associated: \Cungfoo\Model\EtablissementServiceComplementaire
        setter:     addServiceComplementaire
        filter:     filterByServiceComplementaireId
      ACTIVITES:
        model:      \Cungfoo\Model\Activite
        associated: \Cungfoo\Model\EtablissementActivite
        setter:     addActivite
        filter:     filterByActiviteId
      DESTI:
        model:      \Cungfoo\Model\Destination
        associated: \Cungfoo\Model\EtablissementDestination
        setter:     addDestination
        filter:     filterByDestinationId