pays:
    - pays.france
    - pays.afghanistan
    - pays.afriqueDuSud
    - pays.albanie

naturesSinistre:
    - annulation.natureSinistre.annulation
    - annulation.natureSinistre.interruption

suitesSinistre:
    - annulation.suiteSinistre.maladie
    - annulation.suiteSinistre.accident
    - annulation.suiteSinistre.autre