date:
    debut_saison: 2012-04-01
    fin_saison: 2012-10-15
demande_annulation:
    mail: sinistres@campez-couvert.com
    from_mail: no-reply@vacances-directes.com
    from: Vacances Directes
    sujet: Demande d'annulation
httpcache:
    static: 2592000 # 30 days
    long: 86400 # 1 day
    medium: 3600 # 1 h
    short: 600 # 10 min
    home: 3600 # 1 h
    camping: 3600 # 1 h
