title: "menu.title"
items:
    destination:
        title:      "menu.destinations"
        route:      "menu_destinations"
        countQuery: "\\Cungfoo\\Model\\EtablissementPeer::getNbEtablissements"
    bonsplans:
        title:      "menu.bons_plans"
        route:      "menu_bons_plans"
