title: "menu.title"
items:
    destinations:
        title:      "menu.destinations"
        route:      "menu_destinations"
        countQuery: "\\Cungfoo\\Model\\EtablissementPeer::getNbEtablissements"
