menu:
    title: menu.title
    items:
        destinations:
            title:    menu.destinations
            route:    destinations_submenu
        locations:
            title:    menu.locations
            route:    locations_submenu
        bons_plans:
            title:    menu.bons_plans
            route:    bons_plans_submenu
        vacances:
            title:    menu.vacances
            route:    vacances_submenu
        weekends:
            title:    menu.weekends
            route:    weekends_submenu