title: "menu.title"
items:
    destinations:
        title:      "menu.destinations"
        route:      "menu_destinations"
        countQuery: "\\Cungfoo\\Model\\EtablissementPeer::getNbEtablissements"
    bons_plans:
        title:      "menu.bons_plans"
        route:      "menu_bons_plans"
