title: "menu.title"
items:
    destination:
        title:      "menu.destinations"
        route:      "menu_destinations"
        countQuery: "\\Cungfoo\\Model\\EtablissementPeer::getNbEtablissements"
    location:
        title:      "menu.locations"
        route:      "menu_locations"
    bonsplans:
        title:      "menu.bons_plans"
        route:      "menu_bons_plans"
        countQuery: "\\Cungfoo\\Model\\BonPlanPeer::getNbBonsPlansActifs"
        hideCount:  true
